// <auto-generated />
using System;
using ERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.Migrations
{
    [DbContext(typeof(ERPContext))]
    partial class ERPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP.Models.County", b =>
                {
                    b.Property<int>("countyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("countyId"));

                    b.Property<string>("countyTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("countyId");

                    b.ToTable("Counties");

                    b.HasData(
                        new
                        {
                            countyId = 1,
                            countyTitle = "شعبه1"
                        },
                        new
                        {
                            countyId = 2,
                            countyTitle = "شعبه2"
                        },
                        new
                        {
                            countyId = 3,
                            countyTitle = "شعبه3"
                        });
                });

            modelBuilder.Entity("ERP.Models.CountyLevel", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<int?>("EmployeesuserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("department")
                        .HasColumnType("int");

                    b.Property<string>("education")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employmentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tel")
                        .HasColumnType("bigint");

                    b.Property<string>("userPass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("workingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.HasIndex("EmployeesuserId");

                    b.ToTable("CountyLevels");
                });

            modelBuilder.Entity("ERP.Models.Department", b =>
                {
                    b.Property<int>("departmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("departmentId"));

                    b.Property<string>("departmentTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("departmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            departmentId = 1,
                            departmentTitle = "شعبه1"
                        },
                        new
                        {
                            departmentId = 2,
                            departmentTitle = "شعبه2"
                        },
                        new
                        {
                            departmentId = 3,
                            departmentTitle = "شعبه3"
                        });
                });

            modelBuilder.Entity("ERP.Models.DistrictLevel", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<int?>("EmployeesuserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("county")
                        .HasColumnType("int");

                    b.Property<string>("dateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("department")
                        .HasColumnType("int");

                    b.Property<string>("education")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employmentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tel")
                        .HasColumnType("bigint");

                    b.Property<string>("userPass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("workingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.HasIndex("EmployeesuserId");

                    b.ToTable("DistrictLevels");
                });

            modelBuilder.Entity("ERP.Models.DocumentUploadCountyLevel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("dataBytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("department")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fileFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ownerUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roleUploader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("uploadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("documentUploadCountyLevels");
                });

            modelBuilder.Entity("ERP.Models.DocumentUploadDistrictLevel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("county")
                        .HasColumnType("int");

                    b.Property<byte[]>("dataBytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("department")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fileFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ownerUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roleUploader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("uploadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("documentUploadDistrictLevels");
                });

            modelBuilder.Entity("ERP.Models.DocumentUploadProvinceLevel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("dataBytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("department")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fileFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ownerUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roleUploader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("uploadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("documentUploadProvinceLevels");
                });

            modelBuilder.Entity("ERP.Models.Employees", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("country")
                        .HasColumnType("int");

                    b.Property<string>("dateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("department")
                        .HasColumnType("int");

                    b.Property<string>("education")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employmentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tel")
                        .HasColumnType("bigint");

                    b.Property<string>("userPass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("workingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            IsDelete = false,
                            RegisterDate = new DateTime(2023, 8, 24, 0, 47, 29, 707, DateTimeKind.Local).AddTicks(7908),
                            address = "کرج",
                            area = "استان",
                            country = 0,
                            dateOfBirth = "1377/02/20",
                            department = 1,
                            education = "کارشناسی",
                            employmentStatus = "رسمی",
                            fName = "اشکان",
                            gender = "مرد",
                            lName = "مطهری",
                            maritalStatus = "مجرد",
                            nationalCode = "0021047022",
                            role = "مدیریت",
                            tel = 9351225600L,
                            userPass = "123",
                            workingStatus = "فعال"
                        });
                });

            modelBuilder.Entity("ERP.Models.Employment", b =>
                {
                    b.Property<int>("EmploymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmploymentId"));

                    b.Property<string>("EmploymentTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmploymentId");

                    b.ToTable("Employments");

                    b.HasData(
                        new
                        {
                            EmploymentId = 1,
                            EmploymentTitle = "رسمی"
                        },
                        new
                        {
                            EmploymentId = 2,
                            EmploymentTitle = "پیمانی"
                        },
                        new
                        {
                            EmploymentId = 3,
                            EmploymentTitle = "قراردادی"
                        },
                        new
                        {
                            EmploymentId = 4,
                            EmploymentTitle = "آزمایشی"
                        });
                });

            modelBuilder.Entity("ERP.Models.Gender", b =>
                {
                    b.Property<int>("genderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("genderId"));

                    b.Property<string>("genderTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("genderId");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            genderId = 1,
                            genderTitle = "مرد"
                        },
                        new
                        {
                            genderId = 2,
                            genderTitle = "زن"
                        });
                });

            modelBuilder.Entity("ERP.Models.Marital", b =>
                {
                    b.Property<int>("maritalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("maritalId"));

                    b.Property<string>("maritalTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maritalId");

                    b.ToTable("Maritals");

                    b.HasData(
                        new
                        {
                            maritalId = 1,
                            maritalTitle = "مجرد"
                        },
                        new
                        {
                            maritalId = 2,
                            maritalTitle = "متاهل"
                        });
                });

            modelBuilder.Entity("ERP.Models.ProvinceLevel", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<int?>("EmployeesuserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("department")
                        .HasColumnType("int");

                    b.Property<string>("education")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employmentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tel")
                        .HasColumnType("bigint");

                    b.Property<string>("userPass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("workingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.HasIndex("EmployeesuserId");

                    b.ToTable("ProvinceLevel");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            IsDelete = false,
                            RegisterDate = new DateTime(2023, 8, 24, 0, 47, 29, 707, DateTimeKind.Local).AddTicks(7759),
                            address = "کرج",
                            dateOfBirth = "1377/02/20",
                            department = 1,
                            education = "کارشناسی",
                            employmentStatus = "رسمی",
                            fName = "اشکان",
                            gender = "مرد",
                            lName = "مطهری",
                            maritalStatus = "مجرد",
                            nationalCode = "0021047022",
                            role = "مدیریت",
                            tel = 9351225600L,
                            userPass = "123",
                            workingStatus = "فعال"
                        });
                });

            modelBuilder.Entity("ERP.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            IsDelete = false,
                            RoleTitle = "مدیریت"
                        },
                        new
                        {
                            RoleId = 2,
                            IsDelete = false,
                            RoleTitle = "معاونت فناوری اطلاعات"
                        },
                        new
                        {
                            RoleId = 3,
                            IsDelete = false,
                            RoleTitle = "معاونت سیاسی"
                        },
                        new
                        {
                            RoleId = 4,
                            IsDelete = false,
                            RoleTitle = "معاونت فرهنگی"
                        },
                        new
                        {
                            RoleId = 5,
                            IsDelete = false,
                            RoleTitle = "معاونت اجتماعی"
                        },
                        new
                        {
                            RoleId = 6,
                            IsDelete = false,
                            RoleTitle = "معاونت مالی"
                        },
                        new
                        {
                            RoleId = 7,
                            IsDelete = false,
                            RoleTitle = "معاونت امور فرا سطح"
                        },
                        new
                        {
                            RoleId = 8,
                            IsDelete = false,
                            RoleTitle = "معاونت توسعه و پشتیبانی"
                        },
                        new
                        {
                            RoleId = 9,
                            IsDelete = false,
                            RoleTitle = "معاونت منابع انسانی"
                        },
                        new
                        {
                            RoleId = 10,
                            IsDelete = false,
                            RoleTitle = "معاونت حراست"
                        });
                });

            modelBuilder.Entity("ERP.Models.TransferDocumentsBetweenLevels", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("CountyDestination")
                        .HasColumnType("int");

                    b.Property<int>("CountyOrigin")
                        .HasColumnType("int");

                    b.Property<int>("DistrictDestination")
                        .HasColumnType("int");

                    b.Property<int>("DistrictOrigin")
                        .HasColumnType("int");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("ProvinceDestination")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceOrigin")
                        .HasColumnType("int");

                    b.Property<string>("contentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("dataBytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fileFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roleReceiver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roleUploader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("uploadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("userReceiverArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userReceiverId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userUploaderArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userUploaderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("transferDocuments");
                });

            modelBuilder.Entity("ERP.Models.CountyLevel", b =>
                {
                    b.HasOne("ERP.Models.Employees", "Employees")
                        .WithMany("CountyLevels")
                        .HasForeignKey("EmployeesuserId");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ERP.Models.DistrictLevel", b =>
                {
                    b.HasOne("ERP.Models.Employees", "Employees")
                        .WithMany("DistrictLevels")
                        .HasForeignKey("EmployeesuserId");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ERP.Models.DocumentUploadCountyLevel", b =>
                {
                    b.HasOne("ERP.Models.CountyLevel", "countyLevel")
                        .WithOne("DocumentUploadCountyLevels")
                        .HasForeignKey("ERP.Models.DocumentUploadCountyLevel", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("countyLevel");
                });

            modelBuilder.Entity("ERP.Models.DocumentUploadDistrictLevel", b =>
                {
                    b.HasOne("ERP.Models.DistrictLevel", "districtLevel")
                        .WithOne("DocumentUploadDistrictLevels")
                        .HasForeignKey("ERP.Models.DocumentUploadDistrictLevel", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("districtLevel");
                });

            modelBuilder.Entity("ERP.Models.DocumentUploadProvinceLevel", b =>
                {
                    b.HasOne("ERP.Models.ProvinceLevel", "provinceLevel")
                        .WithOne("DocumentUploadProvinces")
                        .HasForeignKey("ERP.Models.DocumentUploadProvinceLevel", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("provinceLevel");
                });

            modelBuilder.Entity("ERP.Models.ProvinceLevel", b =>
                {
                    b.HasOne("ERP.Models.Employees", "Employees")
                        .WithMany("ProvinceLevels")
                        .HasForeignKey("EmployeesuserId");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ERP.Models.CountyLevel", b =>
                {
                    b.Navigation("DocumentUploadCountyLevels");
                });

            modelBuilder.Entity("ERP.Models.DistrictLevel", b =>
                {
                    b.Navigation("DocumentUploadDistrictLevels");
                });

            modelBuilder.Entity("ERP.Models.Employees", b =>
                {
                    b.Navigation("CountyLevels");

                    b.Navigation("DistrictLevels");

                    b.Navigation("ProvinceLevels");
                });

            modelBuilder.Entity("ERP.Models.ProvinceLevel", b =>
                {
                    b.Navigation("DocumentUploadProvinces");
                });
#pragma warning restore 612, 618
        }
    }
}
